
settings:
  token: ''
  chat-prefix: "§bDiscord: "


  guild: ""
  log-channel: ""
  rules-channel: ""
  announce-channel: ""
  mute-role: ""
  voice-mute-role: ""
  reports-channel: ""
  command_prefix: 'ob!'

  trello:
    enabled: true
    API-key: ""
    API-token: ""


ticket-id: 0
case-id: 0
uses: 0
